# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 28 Feb 2015 06:30:18 +0000
*               @ALL          1
*               @user         8
sidebar	@user	2
playground:*	@user	16
playground:*	@ALL	16
