<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Sat, 28 Feb 2015 10:46:23 +0100
 */

$conf['title'] = 'EasyTechWiki';
$conf['start'] = 'Home';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
